info:
  profile: default
  from: git
  test: trace-new！！！
  
test: '{cipher}AQBeHdLO2iZWwHFV7lRwu0j4sWY2ZjBTGjqZc8G8iUAOQ0dundY2X2WYFGk3GxZ24DZTGgwfC2UC7C4EyAemWvGt+lE4yyNnViVEVVPL4yRJWPDq3y/2RLXB/X/01gZvYQsdxQmL37KIBrG1wl9+79uBwR5LKrhhOs3DEQfq7XWYv23ahOF1D08bZOjsavTIynMb96NRucpDaN7fpZ6oJ5JlxMZ0PA0yKycPMU45OEfyS/y8jXglzCeqcqRGtRer+OXhaRQzP4tY7HAAZ7YU2q18QUkzlzPAIVioTp9JCmoqjgL3vy9oIOtFfaaSNkzoPkNK4XVS9Zd6zRjHgyGOFn1uNHhFdqsiknGfETc7fMWfgsVOg0TQdzXAA6bwYSJVmLI='

from: this is from 

server:
  port: 2010
