info:
  profile: default
  from: git
  test: trace-new！！！

test: '{cipher}62abf1e1835cbc3c0eb27bd494aafcfbaa8b77c69f8cc1c3e651e0ba629ad80b'

from: this is from 

#指定微服务名称
#spring.application.name=eureka-client
#指定端口号
server:
  port: 9402
#server.port=9409
#指定eureka注册中心的地址
#eureka.client.serviceUrl.defaultZone=http://localhost:9401/eureka/
#eureka.client.serviceUrl.defaultZone=http://eureka1:9401/eureka/
test: 111
#要注册的admin服务端
spring:
  boot:
    admin:
      url: http://localhost:8790  
#SpringBoot 1.5以后的版本都默认开启端点保护  所有端点在缺省情况下都是安全的。为了简便起见，禁用安全性，这样可以看到所有的端点
management:
  security:
    enabled: false
#eureka.instance.statusPageUrlPath: http://localhost:9402/info
#eureka.instance.healthCheckUrlPath: http://localhost:9402/health

#Sleuth进行采样的日志比例
spring:
  sleuth:
    sampler:
      percentage: 1.0
#Sleuth是否发送追踪日志给Zipkin
spring:
  zipkin:
    enabled: true
#Zipkin的服务端地址
#spring.zipkin.base-url=http://192.168.99.76:9411/
#spring.zipkin.base-url=http://localhost:9411
