#指定微服务名称
spring: 
  application:
    name: eureka-client
#指定端口号
server: 
  port: 9402
#指定eureka注册中心的地址
#eureka.client.serviceUrl.defaultZone=http://localhost:9401/eureka/
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eureka1:9401/eureka/
test: 111
